### ISSUE TITLE
SWIG library should not contain htslib and pbbam

### ISSUE THREAD

**Issue by armintoepfer** [PacificBiosciences/unanimity#16]
From Dave's previous issue:

Install doesn't work if htslib hasn't previously been built

```
(VE) [~/Sources/git/unanimity]$ pip install --upgrade --no-deps .                                                                                                        [master]
Processing /Users/dalexander/Sources/git/unanimity
    Complete output from command python setup.py egg_info:
    Configuring with command `cmake -GNinja -DPYTHON_EXECUTABLE=/Users/dalexander/.virtualenvs/VE/bin/python -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_SWIG=1 /private/var/folders/xn/bd1sbvqj2j1dcpggp7c_g9tspndm75/T/pip-gQhTrk-build`
    -- The CXX compiler identification is AppleClang 7.0.2.7000181
    -- The C compiler identification is AppleClang 7.0.2.7000181
    -- Check for working CXX compiler using: Ninja
    -- Check for working CXX compiler using: Ninja -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Check for working C compiler using: Ninja
    -- Check for working C compiler using: Ninja -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS - Success
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    -- Boost version: 1.60.0
    -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/xn/bd1sbvqj2j1dcpggp7c_g9tspndm75/T/tmpJehEur
    Building with command `/usr/local/bin/ninja`
    ninja: error: '/private/var/folders/xn/bd1sbvqj2j1dcpggp7c_g9tspndm75/T/pip-gQhTrk-build/third-party/htslib/libhts.a', needed by 'ccs', missing and no known rule to make it
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/xn/bd1sbvqj2j1dcpggp7c_g9tspndm75/T/pip-gQhTrk-build/setup.py", line 138, in <module>
        cmake(thisDir)
      File "/var/folders/xn/bd1sbvqj2j1dcpggp7c_g9tspndm75/T/pip-gQhTrk-build/setup.py", line 122, in __call__
        raise RuntimeError("failed to build the project")
    RuntimeError: failed to build the project
```

If we are only building ConsensusCore2, then htslib and pbbam are not dependencies of that.  I think somehow the underlying cmake commmand here is trying to build CCS instead of just the ConsensusCore2 library.  Can we fix that?

**Comment by armintoepfer** [comment]
I've split source into cc2 and the rest https://github.com/PacificBiosciences/unanimity/pull/18
