### ISSUE TITLE
Toolcontract test crashes

### ISSUE THREAD

**Issue by armintoepfer** [PacificBiosciences/unanimity#6]
Uncomment tests/CMakeLists.txt

`# COMMAND __PBTEST_CCS_EXE=${CMAKE_BINARY_DIR}/ccs ${UNY_TestsDir}/python/test_tool_contract.py`

Got this in circleci:

```sh
INFO:root:zmwRanges[CHUNK_INDEX] = [('m140905_042212_sidney_c100564852550000001823085912221377_s1_X0', 32560, 54396)]
INFO:root:SubreadSet = /tmp/tmpOGjNdp.subreadset.xml
INFO:pbcommand.testkit.core:Resolving tool contract to RTC
E
======================================================================
ERROR: test_run_e2e (__main__.TestCCSApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pbcommand/testkit/core.py", line 109, in test_run_e2e
    rtc = self._to_rtc(tc, output_dir, tmp_dir)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pbcommand/testkit/core.py", line 79, in _to_rtc
    return resolve_tool_contract(tc, self.INPUT_FILES, output_dir, tmp_dir, self.MAX_NPROC, self.TASK_OPTIONS, self.IS_DISTRIBUTED)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pbcommand/resolver.py", line 170, in resolve_tool_contract
    output_files, resolved_options, nproc, resources = _resolve_core(tool_contract, input_files, root_output_dir, max_nproc, tool_options, root_tmp_dir)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pbcommand/resolver.py", line 141, in _resolve_core
    resolved_options = _resolve_options(tool_contract, tool_options)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pbcommand/resolver.py", line 64, in _resolve_options
    t=exp_type))
ToolContractError: Incompatible option types. Supplied <type 'float'>. Expected integer```

**Comment by armintoepfer** [comment]
Fixed in https://github.com/PacificBiosciences/unanimity/commit/36895c7ddda5283c0585a3bdeb0efa71ecfa76bc
